#database연동 설정

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_hw?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: gmlals02**
  thymeleaf:
    cache:false


  #spring data jpa설정
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create #기존 테이블을 삭제하고 새로 생성합니다. 모든 데이터가 삭제됩니다.
